Minor tweaks to error handling
sgoudham/mdbook-template pull request #40
Opened 2023-10-07 01:52 UTC by yaleman

Previously when handling incorrectly formatted templates, `mdbook-template` would panic due to using `.unwrap()` while parsing the k/v pairs.

Also applied some clippy lints around borrows/iter usage.

2023-10-16 08:03 UTC, sgoudham commented on src/links.rs
> +                end_index: 57,
I'm curious why this needed to be changed?

2023-10-16 08:12 UTC, sgoudham requested changes
Thank you for your interest and effort into contributing!

Could you please add some happy and sad test cases to verify the logic that has been implemented? We could define multiple correct and incorrect templates and verify that only the correct ones are filtered through.

It might be worth figuring out how to capture the `eprintln!` output but I personally haven't tried this and it might be a slippery slope, happy to hear your thoughts on this!

2023-10-16 08:31 UTC, yaleman commented on src/links.rs
> +                end_index: 57,
Oh, that was my editor stripping a space during `cargo fmt` and me trying to fix it - I've re-wrapped the test string to avoid that in future and reverted the change.

2023-10-16 08:35 UTC, yaleman commented
> Could you please add some happy and sad test cases to verify the logic that has been implemented? We could define multiple correct and incorrect templates and verify that only the correct ones are filtered through.

Sure, will do.

> It might be worth figuring out how to capture the `eprintln!` output but I personally haven't tried this and it might be a slippery slope, happy to hear your thoughts on this!

It's the kind of thing that either needs to throw an error and stop compilation with a clear "this is what went wrong, in x line in y file" - but I was just trying to avoid it panicking on the unwrap to start with 😄

2023-10-29 19:09 UTC, sgoudham approved these changes

2023-10-29 19:12 UTC, merged